from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from tcr_tracker.tracker.views import (
    AllTrackers,
    AllRiders,
    OneTracker,
    OneRider,
    TrackerEdit,
    RiderEdit,
    TrackerTest,
    AddNotes,
    RiderControlpointView,
    ScratchRider,
    GiveRetriveView,
    AddPayment,
    AddRefund,
    RecordIssue,
    TrackerLoginView,
    AssignmentPossessionView
)

urlpatterns = [
    path(r'', RedirectView.as_view(url='/accounts/login', permanent=False), name='index'),
    path('admin/', admin.site.urls),
    path('riders/', AllRiders.as_view(), name='all_riders'),
    path('riders/<int:pk>/', OneRider.as_view(), name='one_rider'),
    path('riders/<int:pk>/edit/', RiderEdit.as_view(), name='rider_edit'),
    path('riders/<int:pk>/assignment_possession/', AssignmentPossessionView.as_view(),
         name='rider_tracker_assignment_possession'),
    path('riders/<int:pk>/notes/', AddNotes.as_view(),
         name='rider_add_notes'),
    path('riders/<int:pk>/control_point/', RiderControlpointView.as_view(),
         name='rider_add_control_point'),
    path('riders/<int:pk>/scratch/', ScratchRider.as_view(),
         name='scratch_rider'),
    path('riders/<int:pk>/add_payment/', AddPayment.as_view(),
         name='add_payment'),
    path('riders/<int:pk>/add_refund/', AddRefund.as_view(),
         name='add_refund'),
    path('riders/<int:pk>/give_retrive/', GiveRetriveView.as_view(),
         name='rider_test'),
    path('trackers/', AllTrackers.as_view(), name='all_trackers'),
    path('trackers/<int:pk>/', OneTracker.as_view(), name='one_tracker'),
    path('trackers/<int:pk>/edit/', TrackerEdit.as_view(), name='tracker_edit'),
    path('trackers/<int:pk>/test/', TrackerTest.as_view(), name='tracker_test'),
    path('trackers/<int:pk>/assignment_possession/', AssignmentPossessionView.as_view(),
         name='tracker_rider_possession'),
    path('trackers/<int:pk>/notes/', AddNotes.as_view(),
         name='tracker_add_notes'),
    path('trackers/<int:pk>/give_retrive/', GiveRetriveView.as_view(),
         name='tracker_give_retrive'),
    path('issues/record/', RecordIssue.as_view(),
         name='record_issue'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/login/', TrackerLoginView.as_view()),
]
