# Generated by Django 2.2.2 on 2019-07-06 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkpoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=50)),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_tcr_staff', models.BooleanField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Riders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('cap_number', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('pairs', 'Pairs'), ('solo', 'Solo')], max_length=50, null=True)),
                ('gender', models.CharField(choices=[('male', 'M'), ('female', 'F')], max_length=10, null=True)),
                ('balance', models.IntegerField(default=0, null=True)),
                ('tcr_id', models.CharField(max_length=10, null=True)),
                ('country_code', models.CharField(max_length=5, null=True)),
                ('hire_tracker', models.BooleanField(null=True)),
                ('tracker_url', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Riders',
            },
        ),
        migrations.CreateModel(
            name='TimeStampedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='RaceStatus',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tracker.TimeStampedModel')),
                ('status', models.CharField(choices=[('pre_race', 'Pre_Race'), ('started', 'Started'), ('finished', 'Finished')], max_length=20)),
            ],
            bases=('tracker.timestampedmodel',),
        ),
        migrations.CreateModel(
            name='Trackers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esn_number', models.CharField(max_length=50)),
                ('working_status', models.CharField(choices=[('working', 'Working'), ('broken', 'Broken'), ('to_be_tested', 'To Be Tested'), ('unknown', 'Unknown')], max_length=50, verbose_name='Working Status')),
                ('loan_status', models.CharField(choices=[('with_rider', 'With Rider'), ('not_loaned', 'Not Loaned'), ('other', 'Other')], max_length=50, null=True)),
                ('last_test_date', models.DateField(null=True)),
                ('purchase_date', models.DateField(null=True)),
                ('warranty_expiry', models.DateField(null=True)),
                ('owner', models.CharField(choices=[('lost_dot', 'Lost Dot'), ('rider_owned', 'Rider Owned'), ('third_party', 'Third Party')], max_length=50)),
                ('tcr_id', models.CharField(max_length=20, null=True)),
                ('test_by', models.CharField(blank=True, max_length=20, null=True)),
                ('clip', models.BooleanField(null=True)),
                ('rider_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trackers_assigned', to='tracker.Riders')),
                ('rider_possess', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trackers_possessed', to='tracker.Riders')),
            ],
            options={
                'verbose_name_plural': 'Trackers',
            },
        ),
        migrations.CreateModel(
            name='RiderCheckpoints',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tracker.TimeStampedModel')),
                ('checkpoint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riders', to='tracker.Riders')),
                ('rider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkpoints', to='tracker.Riders')),
            ],
            bases=('tracker.timestampedmodel',),
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tracker.TimeStampedModel')),
                ('event_type', models.CharField(choices=[('payment_in', 'Payment In'), ('payment_out', 'Payment Out'), ('start_race', 'Start Race'), ('finish_race', 'Finish Race'), ('scratch', 'Scratch'), ('arrive_checkpoint', 'Arrive Checkpoint'), ('add_tracker_assignment', 'Tracker Assigned'), ('remove_tracker_assignment', 'Tracker remove assignment'), ('add_tracker_possession', 'Tracker Possession Add'), ('remove_tracker_possession', 'Tracker Possession Remove'), ('tested_OK', 'Tested OK'), ('tested_broken', 'Tested Broken'), ('add_tracker_assignment', 'Tracker add assignment'), ('remove_tracker_assignment', 'Tracker remove assignment'), ('add_tracker_possession', 'Tracker add possession'), ('remove_tracker_possession', 'Tracker remove possession'), ('add_note', 'Add_note')], max_length=50)),
                ('notes', models.TextField(null=True)),
                ('deposit_change', models.IntegerField(null=True)),
                ('rider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='tracker.Riders')),
                ('tracker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='tracker.Trackers')),
            ],
            bases=('tracker.timestampedmodel',),
        ),
    ]
