# Generated by Django 2.2.2 on 2019-06-16 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riderevents',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='ridernotes',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='trackerevents',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='trackernotes',
            name='datetime',
        ),
        migrations.AlterField(
            model_name='trackers',
            name='rider_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trackers_assigned', to='tracker.Riders'),
        ),
        migrations.AlterField(
            model_name='trackers',
            name='rider_possess',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trackers_possessed', to='tracker.Riders'),
        ),
    ]
