# Generated by Django 2.2.2 on 2019-07-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racestatus',
            name='status',
            field=models.CharField(choices=[('pre_race', 'Pre_Race'), ('started', 'Started'), ('finished', 'Finished')], max_length=20, unique=True),
        ),
    ]
