# Generated by Django 2.2.2 on 2019-06-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riders',
            name='country_code',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='riders',
            name='gender',
            field=models.CharField(choices=[('male', 'M'), ('female', 'F')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='riders',
            name='hire_tracker',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='riders',
            name='tcr_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='riders',
            name='category',
            field=models.CharField(choices=[('pairs', 'Pairs'), ('solo', 'Solo')], max_length=50, null=True),
        ),
    ]
