# Generated by Django 2.2.2 on 2019-06-05 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackers',
            name='rider_assigned',
        ),
        migrations.AddField(
            model_name='trackers',
            name='rider_assigned',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_trackers', to='tracker.Riders'),
        ),
        migrations.RemoveField(
            model_name='trackers',
            name='rider_possess',
        ),
        migrations.AddField(
            model_name='trackers',
            name='rider_possess',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='possessed_trackers', to='tracker.Riders'),
        ),
    ]
