# Generated by Django 2.2.2 on 2019-06-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ridernotes',
            old_name='events',
            new_name='event',
        ),
        migrations.AlterField(
            model_name='riderevents',
            name='event_type',
            field=models.CharField(choices=[('payment_in', 'Payment In'), ('payment_out', 'Payment Out'), ('start_race', 'Start Race'), ('finish_race', 'Finish Race'), ('scratch', 'Scratch'), ('arrive_checkpoint', 'Arrive Checkpoint'), ('add_tracker_assignment', 'Tracker Assigned'), ('remove_tracker_assignment', 'Tracker remove assignment'), ('add_tracker_possession', 'Tracker Possession Add'), ('remove_tracker_possession', 'Tracker Possession Remove')], max_length=50),
        ),
    ]
