# Generated by Django 2.2.2 on 2019-06-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20190620_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='riders',
            name='tracker_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
