# Generated by Django 2.2.2 on 2019-06-19 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20190616_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkpoints',
            old_name='abbriviation',
            new_name='abbreviation',
        ),
        migrations.AlterField(
            model_name='trackernotes',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='tracker.TrackerEvents'),
        ),
        migrations.AlterField(
            model_name='trackernotes',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
