# Generated by Django 2.2.2 on 2019-07-07 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20190706_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='deposit_change',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='tracker.Riders'),
        ),
        migrations.AlterField(
            model_name='events',
            name='tracker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='tracker.Trackers'),
        ),
        migrations.AlterField(
            model_name='trackers',
            name='working_status',
            field=models.CharField(choices=[('working', 'Working'), ('broken', 'Broken'), ('to_be_tested', 'To Be Tested'), ('lost', 'Lost'), ('unknown', 'Unknown')], max_length=50, verbose_name='Working Status'),
        ),
    ]
