# Generated by Django 2.2.3 on 2019-07-10 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20190707_0650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackers',
            old_name='rider_possess',
            new_name='rider_possesed',
        ),
    ]
