# Generated by Django 2.2.3 on 2019-07-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20190710_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='input_by',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
