# Generated by Django 2.2.2 on 2019-06-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20190620_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackers',
            name='clip',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='trackers',
            name='tcr_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trackers',
            name='test_by',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trackers',
            name='loan_status',
            field=models.CharField(choices=[('with_rider', 'With Rider'), ('not_loaned', 'Not Loaned'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trackers',
            name='owner',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='trackers',
            name='working_status',
            field=models.CharField(max_length=50, verbose_name='Working Status'),
        ),
    ]
