# Generated by Django 2.2.3 on 2019-07-10 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_events_input_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderControlPoints',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tracker.TimeStampedModel')),
                ('race_time', models.DateField()),
                ('input_by', models.CharField(max_length=50)),
            ],
            bases=('tracker.timestampedmodel',),
        ),
        migrations.RenameModel(
            old_name='Checkpoints',
            new_name='ControlPoints',
        ),
        migrations.DeleteModel(
            name='RiderCheckpoints',
        ),
        migrations.AddField(
            model_name='ridercontrolpoints',
            name='control_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riders', to='tracker.ControlPoints'),
        ),
        migrations.AddField(
            model_name='ridercontrolpoints',
            name='rider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkpoints', to='tracker.Riders'),
        ),
    ]
