# Generated by Django 2.2.3 on 2019-07-10 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20190710_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='control_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='tracker.ControlPoints'),
        ),
    ]
