# Generated by Django 2.2.2 on 2019-06-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20190621_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_tcr_staff',
            field=models.BooleanField(null=True),
        ),
    ]
