# Generated by Django 2.2.3 on 2019-07-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_events_control_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_collective_user',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='ridercontrolpoints',
            name='race_time_string',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='riders',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('finished', 'Finished'), ('scratched', 'Scratched')], max_length=50, null=True),
        ),
    ]
