# Generated by Django 2.2.3 on 2019-07-11 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_auto_20190710_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riders',
            name='balance',
        ),
        migrations.AlterField(
            model_name='events',
            name='event_type',
            field=models.CharField(choices=[('payment_in', 'Payment In'), ('payment_out', 'Payment Out'), ('start_race', 'Start Race'), ('finish_race', 'Finish Race'), ('scratch', 'Scratch'), ('arrive_checkpoint', 'Arrive Checkpoint'), ('add_tracker_assignment', 'Tracker Assigned'), ('remove_tracker_assignment', 'Tracker remove assignment'), ('add_tracker_possession', 'Tracker Possession Add'), ('remove_tracker_possession', 'Tracker Possession Remove'), ('tested_OK', 'Tested OK'), ('tested_broken', 'Tested Broken'), ('add_tracker_assignment', 'Tracker add assignment'), ('remove_tracker_assignment', 'Tracker remove assignment'), ('add_tracker_possession', 'Tracker add possession'), ('remove_tracker_possession', 'Tracker remove possession'), ('add_note', 'Add_note')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('timestampedmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tracker.TimeStampedModel')),
                ('amount_in_pence', models.IntegerField()),
                ('rider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='tracker.Riders')),
            ],
            bases=('tracker.timestampedmodel',),
        ),
    ]
