# Generated by Django 2.2.3 on 2019-07-12 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_auto_20190712_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='deposit_change',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='tracker.Deposit'),
        ),
    ]
