# Generated by Django 2.2.3 on 2019-07-22 17:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_auto_20190713_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='cap_number',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 1', regex='^.{1}$')]),
        ),
    ]
