# Generated by Django 2.2.3 on 2019-07-22 18:11

from django.db import migrations, models


def add_display_order(apps, schema_editor):
    Riders = apps.get_model('tracker', 'Rider')
    for rider in Riders.objects.all():
        if rider.cap_number:
            try:
                rider.display_order = int(rider.cap_number)
            except ValueError:
                rider.display_order = int(rider.cap_number[:-1])
        else:
            rider.display_order = 1000
        rider.save()

class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_auto_20190722_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='display_order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.RunPython(
            add_display_order
        )
    ]
