# Generated by Django 2.2.3 on 2019-07-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_auto_20190725_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('payment_in', 'Payment In'), ('payment_out', 'Payment Out'), ('start_race', 'Start Race'), ('finish_race', 'Finish Race'), ('scratch', 'Scratch'), ('arrive_checkpoint', 'Arrive Checkpoint'), ('add_tracker_assignment', 'Tracker Assigned'), ('remove_tracker_assignment', 'Tracker remove assignment'), ('add_tracker_possession', 'Tracker Possession Add'), ('remove_tracker_possession', 'Tracker Possession Remove'), ('tested_OK', 'Tested OK'), ('tested_broken', 'Tested Broken'), ('add_tracker_assignment', 'Tracker add assignment'), ('remove_tracker_assignment', 'Tracker remove assignment'), ('add_tracker_possession', 'Tracker add possession'), ('remove_tracker_possession', 'Tracker remove possession'), ('add_note', 'Add_note'), ('attend_registation', 'Attend Registration')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ridercontrolpoint',
            name='race_time',
            field=models.DateTimeField(),
        ),
    ]
