# Generated by Django 2.2.3 on 2019-08-28 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_auto_20190727_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='test_status',
            field=models.CharField(choices=[('to_be_tested', 'To Be Tested'), ('visual_check_OK', 'Visual Check OK'), ('visual_check_FAIL', 'Visual Check Fail'), ('ping_test_OK', 'Ping Test OK'), ('ping_test_FAIL', 'Ping Test Fail')], default='to_be_tested', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rider',
            name='status',
            field=models.CharField(blank=True, choices=[('dns', 'DNS'), ('active', 'Active'), ('finished', 'Finished'), ('scratched', 'Scratched')], default='active', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='timestampedmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.Profile'),
        ),
    ]
