# Generated by Django 2.2.3 on 2019-09-23 17:39

from django.db import migrations, models


def add_control_points(apps, _):
    ControlPoint = apps.get_model('tracker', 'ControlPoint')
    cps = [
        {
            'name': 'Control Point One',
            'abbreviation': 'CP1',
            'race': 'TPR'
        },
        {
            'name': 'Control Point Two',
            'abbreviation': 'CP2',
            'race': 'TPR'
        },
        {
            'name': 'Control Point Three',
            'abbreviation': 'CP3',
            'race': 'TPR'
        },
        {
            'name': 'Finish',
            'abbreviation': 'Finish',
            'race': 'TPR'
        }
    ]
    for cp in cps:
        ControlPoint.objects.create(**cp)


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0019_auto_20190923_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlpoint',
            name='race',
            field=models.CharField(default='TCR', max_length=3),
        ),
        migrations.RemoveField(
            model_name='controlpoint',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='controlpoint',
            name='longitude',
        ),
        migrations.RunPython(
            add_control_points,
            reverse_code=migrations.RunPython.noop
        )
    ]
