# Generated by Django 2.2.3 on 2019-09-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_controlpoint_race'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='race',
            field=models.CharField(default='TCR', max_length=3),
        ),
    ]
