# Generated by Django 2.2.3 on 2019-09-23 17:51

from django.db import migrations, models

# loop over all trackers, and if they start with AOS then active tracker should be false
from django.db.models import Q


def set_aos_trackers_to_false_active(apps, _):
    trackers = apps.get_model('tracker', 'Tracker').objects.filter(
        Q(tcr_id__startswith='AOS') | Q(tcr_id__startswith='RIDER_OWN'))
    for tkr in trackers:
        tkr.active_tracker = False
        tkr.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_rider_race'),
    ]

    operations = [
        migrations.AddField(
            model_name='racestatus',
            name='race',
            field=models.CharField(default='TCR', max_length=3),
        ),
        migrations.AddField(
            model_name='tracker',
            name='active_tracker',
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(
            set_aos_trackers_to_false_active, reverse_code=migrations.RunPython.noop
        )
    ]
