# Generated by Django 2.2.4 on 2019-09-23 20:08

from django.db import migrations, models


def add_tcr_to_all_events(apps, _):
    Events = apps.get_model('tracker', 'Event')
    Events.objects.all().update(race='TCR')

class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0022_auto_20190923_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='race',
            field=models.CharField(choices=[('TCR', 'TCR'), ('TPR', 'TPR')], max_length=50, null=True),
        ),
        migrations.RunPython(
            add_tcr_to_all_events,
            reverse_code=migrations.RunPython.noop

        )
    ]
