# Generated by Django 2.2.3 on 2019-09-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0024_rider_offset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='attended_registration_desk',
            field=models.NullBooleanField(),
        ),
    ]
