# Generated by Django 2.2.3 on 2019-10-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0026_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridercontrolpoint',
            name='position',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('payment_in', 'Payment In'), ('payment_out', 'Payment Out'), ('start_race', 'Start Race'), ('finish_race', 'Finish Race'), ('scratch', 'Scratch'), ('arrive_checkpoint', 'Arrive Checkpoint'), ('add_tracker_assignment', 'Tracker Assigned'), ('remove_tracker_assignment', 'Tracker remove assignment'), ('add_tracker_possession', 'Tracker Possession Add'), ('remove_tracker_possession', 'Tracker Possession Remove'), ('add_tracker_assignment', 'Tracker add assignment'), ('remove_tracker_assignment', 'Tracker remove assignment'), ('add_tracker_possession', 'Tracker add possession'), ('remove_tracker_possession', 'Tracker remove possession'), ('add_note', 'Add_note'), ('attend_registation', 'Attend Registration'), ('to_be_tested', 'To Be Tested'), ('visual_check_OK', 'Visual Check OK'), ('visual_check_FAIL', 'Visual Check Fail'), ('ping_test_OK', 'Ping Test OK'), ('ping_test_FAIL', 'Ping Test Fail'), ('missing', 'Missing'), ('no_spot_plan', 'No Spot Plan')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='test_status',
            field=models.CharField(choices=[('to_be_tested', 'To Be Tested'), ('visual_check_OK', 'Visual Check OK'), ('visual_check_FAIL', 'Visual Check Fail'), ('ping_test_OK', 'Ping Test OK'), ('ping_test_FAIL', 'Ping Test Fail'), ('missing', 'Missing'), ('no_spot_plan', 'No Spot Plan')], default='to_be_tested', max_length=50, null=True),
        ),
    ]
