# Generated by Django 2.2.3 on 2019-11-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0027_auto_20191012_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='ignore_refund',
            field=models.NullBooleanField(default=None),
        ),
    ]
